language: java
dist: xenial
jobs:
  include:
    - stage: Tests
      name: "test1"
      script: 
        - echo "Running unit tests (1)"
       # - apt-get install travis-conditions
        - echo $a
        - echo "$a"
        #- travis-conditions parse "branch = foo"
#after_success:
 
    
