language: java
dist: xenial
jobs:
  include:
    - stage: Tests
      name: "test1"
      script: 
        - echo "Running unit tests (1)"
        - apt-get install travis-conditions
        - echo $a
        - echo "$a"
        - echo "$variable1"
        - travis-conditions parse "branch = foo"

after_script:
 - echo " after script message"

after_success:
 - echo  " success msg"
after_failure:
 - echo " this is wrong"
 
    
