language: java

stages:
   - Tests
   - Tests2
   - name: Test3
     if: branch = master
jobs:
   include:
    - stage: Tests
      name: "test1"
      script: 
        - echo "Running unit tests (1)"
    - stage: Tests2
      script: 
        - echo "Running unit tests (2)"
      name: "test2"
    - stage: Test3
      name: "Test3"
      script: echo "Running unit tests 3"
