language: java

jobs:
  include:
    - stage: Tests
      name: "test1"
      script: 
        - echo "Running unit tests (1)"
        - apt-get install travis-conditions
      #  - travis-conditions eval "branch = foo" --data '{"branch": "foo"}'
    
